//------------------------------------------------------------------------------
// <auto-generated>
//     Este código lo generó una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace _03_00_Uso_de_BaseDeDatos_en_interfaz_de_usuario
{
    public partial class _Default
    {
    }
}
