//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace _03_00_Uso_de_BaseDeDatos_en_interfaz_de_usuario {
    
    
    public partial class ViewSwitcher {
    }
}
